### ISSUE TITLE
Please bring back the old way to edit Tags fast

### ISSUE THREAD

**Issue by Rartist** [toshiaki1729/stable-diffusion-webui-dataset-tag-editor#22]
In the older version of your Extension it was easy to select and change tags fast.
Because of all the additions and reorganizing that somehow changed.

As I understand now a Tag has to be selected and then copied over to the "Search text" field to change it in the "replace text" field.
(or alternatively under Common tags, but since that shows all common tags for the selection, that can be finicky)

A few times I tried to edit it without first copying it to "Search text" and got an interesting bug that basically turns all "_" into the tag resulting in a long tag like "black dogblack dogblack dogblack dogblack dog".

A way to do that could be to auto-copy the selected tags into "Search text" (similiar to the old implementation?).

Looking forward to your thoughts on this.

**Comment by toshiaki1729** [comment]
The reason for displaying "common tags" is to handle "OR" and "NOT" filters.
However, as you point out, It may be too redundant especially with images that have very similar tags.
I will try to add an option to show only the tags selected in positive filter.
This will work the same as before when you use only use "AND" filters.

**Comment by Rartist** [comment]
Great.

Why does "none" exist though? Couldn't "and" be the standard and "or" the alternative?

**Comment by toshiaki1729** [comment]
I think I had some reason when I implemented the "OR" and "NOT" feature, however, it should be really tiny thing because I don't remember.
I changed the default filter and the order of filters, remaining NONE option.
I'm not sure, but the NONE could be useful since it can deactivate filter without changing tag selection, maybe.

**Comment by toshiaki1729** [comment]
> Could you make "And" the default, since None is used in less cases?

Yes! I have changed the UI as you said.
Please pull the latest commit f6f42df9ca0c1bf7564140cec8a01ff7b9462287.

**Comment by Rartist** [comment]
I did that. Maybe I need to restart everything instead of just Gradio.

**Comment by toshiaki1729** [comment]
Yes… the change won't be applied automatically because the `ui.py` is not directly under the `scripts` folder.
Please restart the webui if it you don't mind.
I think importing modules dynamically can completely solve this problem, like the way in [depthmap2mask](https://github.com/Extraltodeus/depthmap2mask).
I'm considering to do something similar in tag-editor.

**Comment by toshiaki1729** [comment]
> I'm considering to do something similar in tag-editor.

But I might have to rebuild the whole extension.

**Comment by Rartist** [comment]
It works now. :)

If rebuilding the Extension is a lot of work with no obvious gain maybe that's a project for later.

Or would you gain substantial benefits like improved handling of datasets?

**Comment by toshiaki1729** [comment]
> Or would you gain substantial benefits like improved handling of datasets?

I think nothing but the easier reloading will be.
However, it also can make testing and debugging easier.

**Comment by Rartist** [comment]
That makes sense.

Even though it's egoistic - I'd really prefer it if you took a look at the Wd1_4 tagger and auto clearing "Caption of Selected Image" & "Edit Caption" first. xD (hides)
