### ISSUE TITLE
[Feature Request] Standalone version

### ISSUE THREAD

**Issue by ruSauron** [toshiaki1729/stable-diffusion-webui-dataset-tag-editor#65]
Is it possible to make a separate launcher that doesn't require automatic1111 webui to run?
So that even when webui updates and breaks everything, you can still use your script. May be without interrogators if its hard to implement them.
So you could run a separate .py script without making a big load of video memory from the whole webui. Or better yet, make possible to use this extension as a utility for **bmaltais/kohya_ss** training script

**Comment by toshiaki1729** [comment]
Since this extension is mostly independent from webUI scripts, it is not too difficult to make it standalone as long as using gradio.

The dependent features are as follows;
- also independent from webUI main feature (these can be implemented manually)
  - BLIP, DeepDanbooru
  - CLIP (raw text tokenizer)
- dependent on future webUI update (impossible to support permanently)
  - hijacked CLIP tokenizer (with embedding, emphasis, …)

However, actually I want to use something other than gradio (like [streamlit](https://streamlit.io/)) if I make the standalone version.
This is because gradio cannot accept custom component (component is something like button or textbox) without changing gradio library folder itself (this makes distribution of custom component difficult).
Custom component is an easy way to add more user-friendly UIs. I need this because I don't have any skill in making frontend UI on web browser.

**Comment by ShaguarWKL** [comment]
with a better UI than 1111 UI. This extension is so great for pre-training prep but 1111 UI drives me nuts. Hope this happens in the future.

**Comment by ruSauron** [comment]
fake "standalone version" (actually it's fresh automatic1111 installation), you need 10-11 gb on your hdd/ssd.
Copy the text below into notepad and save as **install.bat** in the folder where you want to have a separate version of dataset-tag-editor.
The installation will take about 5-30 minutes (depends on your download speed, CPU and SSD)
Next time use the file **dataset-tag-editor\dataset.bat** to start it (startup time 15-120s)
I chose port 7862 because 7860 is the standard webui port and I usually run bmaltais/kohya_ss on 7681

```
git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui.git dataset-tag-editor
cd "dataset-tag-editor"
git reset --hard 2f01814
cd extensions
git clone -b v0.1.2 https://github.com/toshiaki1729/stable-diffusion-webui-dataset-tag-editor.git
cd ..
echo title dataset-tag-editor > dataset.bat
echo set COMMANDLINE_ARGS= --lowvram --skip-version-check --autolaunch --theme dark --port 7862 >> dataset.bat
echo call webui.bat >> dataset.bat
echo httpx==0.24.1 >> requirements_versions.txt
echo torchmetrics==0.11.4 >> requirements_versions.txt
call dataset.bat
```

And copy any SD 1.4-1.5 ckpt or safetensors checkpoint to dataset-tag-editor\models\Stable-diffusion

**Comment by IkariDevGIT** [comment]
please a standalone version! @toshiaki1729

**Comment by toshiaki1729** [comment]
Thank you for your patience!
Still WIP and not tested well but released the **Standalone Version**
https://github.com/toshiaki1729/dataset-tag-editor-standalone

**Here is difference from this Extension Version**
(Pros)
- Avoid bugs caused by specific version of gradio
- Much faster startup and running
- Added some captioning interrogators ([GIT](https://huggingface.co/docs/transformers/model_doc/git) ([paper (arXiv)](https://arxiv.org/abs/2205.14100)), [BLIP-2](https://huggingface.co/docs/transformers/model_doc/blip-2) ([paper (arXiv)](https://arxiv.org/abs/2301.12597)): BLIP-2 may extremely heavy), which is mentioned in #33

(Cons)
- Hijacked CLIP tokenizer is not available (which has SDwebUI specific features like embedding, emphasis, …)
- No more support for old Python < 3.9
