### ISSUE TITLE
Filters won't change displayed images

### ISSUE THREAD

**Issue by S0ulMeister** [toshiaki1729/stable-diffusion-webui-dataset-tag-editor#71]
As I filter for tags, the dataset will continue to display all images, even though the bottom it will say "Displayed Images : 6 / 121 total" for example.

EDIT:
Tag-Editor hash: c1c78f597679abb008f3e8f1add84620e1aec35e
Auto1111 commit hash: a9fed7c364061ae6efb37f797b6b522cb3cf7aa2

**Comment by toshiaki1729** [comment]
Thank you.
Please give us your webUI's commit hash and your tag-editor's one first.

**Comment by toshiaki1729** [comment]
> Auto1111 commit hash: a9fed7c364061ae6efb37f797b6b522cb3cf7aa2

https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/a9fed7c364061ae6efb37f797b6b522cb3cf7aa2
This webUI version is not compatible with tag-editor v0.2.0 .
I recommend you to downgrade tag-editor version to v0.1.2, if you don't need webUI's latest feature. This is because tag-editor has many problems with the latest webUI.


Compatibility:
https://github.com/toshiaki1729/stable-diffusion-webui-dataset-tag-editor/releases

**Comment by Luke-L** [comment]
is this still a problem? with smaller datasets (<60img) i dont have this problem, but larger ones still do this.
